services:
  - type: web
    name: n8n-scalping-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: changeme
      - key: N8N_PORT
        value: 5678
